// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"google-auth/biz/handler"
	"google-auth/biz/middleware"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.Any("/login", middleware.AuthMiddleware.LoginHandler)

	// need login
	needLogin := r.Use(middleware.AuthMiddleware.MiddlewareFunc())
	needLogin.GET("/user/info", handler.GetUserInfo)
	needLogin.POST("logout", middleware.AuthMiddleware.LogoutHandler)
}
