// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"google-auth/biz/middleware"
)

func main() {
	h := server.Default()
	h.Use(middleware.CorsMw())

	middleware.InitAuthMiddleware()

	register(h)
	h.Spin()
}
